### ISSUE TITLE
Невозможно изменить настройки подключения к базе данных

### ISSUE THREAD

**Issue by EgorBanin** [Catkitkatars/Garage#1]
В текущей реализации нельзя изменить настройки подключения к базе данных, не изменив код класса database/Connect.php. Надо добавить специальный файл конфигурации, в котором можно будет менять настройки всего приложения (в том числе и настройки подключения к базе данных).

**Comment by Catkitkatars** [comment]
Починил. Добавил отдельный файл config.php с данными для входа. Чуть переделал Connect и связанные классы и подключения в файлы. Проверил, проект работает.
